CREATE TABLE User (
    userID SERIAL PRIMARY KEY,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    userAge INT NOT NULL
    userWeight INT NOT NULL,
    email VARCHAR(50) NULL,
    phoneNumber VARCHAR(50) NULL,
    isActive BOOLEAN NOT NULL DEFAULT TRUE,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Food (
    foodID SERIAL PRIMARY KEY,
    userID INT FOREIGN KEY REFERENCES User(userID),
    foodName VARCHAR(50) NOT NULL,
    calories INT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE FoodLog (
    foodLogID SERIAL PRIMARY KEY,
    userID INT FOREIGN KEY REFERENCES User(userID),
    foodID INT FOREIGN KEY REFERENCES Food(foodID)
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
